version: '3.8'
services:
  app:
    container_name: telecom-survey-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb+srv://shakthi:shakthi@cluster0.shxml.mongodb.net/fleet_management_prehoto?retryWrites=true&w=majority
      - JWT_SECRET=shakthi
    restart: always
