version: '3.8'

services:
  app:
    container_name: telecom-survey-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/fleet_management_prehoto
      - JWT_SECRET=shakthi  # In production, use secrets or .env
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: mongodb
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fleet_management_prehoto
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
